# Generated by Django 5.1.7 on 2025-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20250313_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=20),
        ),
    ]
